In [1]:
import numpy as np

In [2]:
# creating a 5x5 matrix with random integers between 1 and 20
matrix = np.random.randint(1, 21, size=(5, 5))

In [3]:
matrix

array([[17, 15, 14, 11, 14],
       [ 3,  6,  5, 14,  5],
       [ 2,  6, 17,  1,  2],
       [16, 13, 18,  2,  2],
       [ 6,  2,  6, 15,  3]], dtype=int32)

In [6]:
matrix=np.arange(1,17).reshape(4,4)

In [9]:
matrix
matrix[np.diag_indices(4)] = 0
print(matrix)

[[ 0  2  3  4]
 [ 5  0  7  8]
 [ 9 10  0 12]
 [13 14 15  0]]


In [12]:
matrix=np.arange(1,37).reshape(6,6)
array=matrix[2:5,1:4]
print(array)

[[14 15 16]
 [20 21 22]
 [26 27 28]]


In [22]:
matrix1=np.random.randint(100, size=(3,4))
matrix2=np.random.randint(100, size=(3,4))
print(matrix1)
print(matrix2)
# element-wise multiplication
result = matrix1 * matrix2
print(result)
# matrix multiplication
result = np.dot(matrix1, matrix2.T)
print(result)

# addition
result = matrix1 + matrix2
print(result)

[[68 61 70 52]
 [76 75  1 74]
 [14 49 39 26]]
[[51 78 91 78]
 [21 32 78 74]
 [52 49 86 58]]
[[3468 4758 6370 4056]
 [1596 2400   78 5476]
 [ 728 2401 3354 1508]]
[[18652 12688 15561]
 [15589  9550 12005]
 [10113  6828  7991]]
[[119 139 161 130]
 [ 97 107  79 148]
 [ 66  98 125  84]]


In [24]:
matx=np.arange(1,17).reshape(4,4)
# row wise sum
row_sum = np.sum(matx, axis=1)
print(row_sum)
# column wise sum
col_sum = np.sum(matx, axis=0)
print(col_sum)

[10 26 42 58]
[28 32 36 40]


In [25]:
matrix = np.arange(1, 26).reshape(5, 5)
sd=np.std(matrix)
print(sd)
# mean
mean=np.mean(matrix)
print(mean)
# median
median=np.median(matrix)
print(median)
# variance
variance=np.var(matrix)
print(variance)

7.211102550927978
13.0
13.0
52.0


In [27]:
matrix=np.arange(1,10).reshape(3,3)
# normalization
normalized_matrix = (matrix - np.mean(matrix)) / np.std(matrix)
print(normalized_matrix)

[[-1.54919334 -1.161895   -0.77459667]
 [-0.38729833  0.          0.38729833]
 [ 0.77459667  1.161895    1.54919334]]


In [28]:
# use of broadcasting
matrix1=np.random.randint(1,10, size=(3,3))
array1=np.random.randint(1,10, size=(3,1))
matrix1 = matrix1 + array1
print(matrix1)

[[ 9 14 11]
 [10 16 13]
 [12 12  8]]


In [29]:
print("Matrix 1:", matrix1)
temp=np.linalg.det(matrix1)
print("Determinant of Matrix 1:", temp)
# inverse of matrix
temp=np.linalg.inv(matrix1)
print("Inverse of Matrix 1:", temp)
# eigenvalues and eigenvectors
temp=np.linalg.eig(matrix1)
print("Eigenvalues of Matrix 1:", temp[0])
print("Eigenvectors of Matrix 1:", temp[1])
# singular value decomposition

Matrix 1: [[ 9 14 11]
 [10 16 13]
 [12 12  8]]
Determinant of Matrix 1: 20.00000000000006
Inverse of Matrix 1: [[-1.4   1.    0.3 ]
 [ 3.8  -3.   -0.35]
 [-3.6   3.    0.2 ]]
Eigenvalues of Matrix 1: [35.38955104 -2.12340353 -0.26614751]
Eigenvectors of Matrix 1: [[-0.55920509 -0.23859058  0.20090566]
 [-0.6409445  -0.47566044 -0.68398389]
 [-0.52581348  0.84665322  0.70128664]]


In [30]:
import numpy.ma as ma

# Create a masked array of shape (4, 4) with random integers
array = np.random.randint(1, 21, size=(4, 4))
masked_array = ma.masked_greater(array, 10)
print("Original array:")
print(array)
print("Masked array:")
print(masked_array)

# Compute the sum of the unmasked elements
sum_unmasked = masked_array.sum()
print("Sum of unmasked elements:", sum_unmasked)

Original array:
[[14  2  1 20]
 [ 2 15  3  6]
 [ 1  7 17  1]
 [ 4 14  3 11]]
Masked array:
[[-- 2 1 --]
 [2 -- 3 6]
 [1 7 -- 1]
 [4 -- 3 --]]
Sum of unmasked elements: 30
